
---
- hosts: 
    - vpnservers
    - cdns
    - proxies
    - masters

  become: False
  gather_facts: yes

  pre_tasks:

  roles:
    - dj-wasabi.telegraf

  vars:
    telegraf_agent_package_state: latest
    telegraf_agent_hostname: "{{ inventory_hostname }}"
    telegraf_agent_flush_jitter: 4
    telegraf_agent_output:
      - type: influxdb
        config:
          - urls = ["http://45.142.214.244:8086"]
          - database = "telegraf"
          - precision = "s"
          - username = "telegraf"
          - password = "KYHxGO2hav"
    telegraf_plugins_default:
      - plugin: cpu
        config:
          - percpu = true
      - plugin: diskio
      - plugin: disk
        config:
          - 'ignore_fs = ["tmpfs", "devtmpfs", "devfs", "overlay", "aufs", "squashfs"]'
      - plugin: io
      - plugin: mem
      - plugin: net
        config:
          - 'interfaces = ["eth*", "en*"]'
      - plugin: netstat
      - plugin: processes
      - plugin: swap
      - plugin: system

