
#################### make sure Python is installed

- hosts:
    - all
  become: True
  gather_facts: no
  pre_tasks:
    - name: Install Python
      include: install.python.yml

#################### NoLogs:

- hosts: 
    - all
  
  become: True
  gather_facts: yes

  roles:
    - xoom.nologs

#################### Firewall:

- import_playbook: __xoom.firewall.yml 

##################### NRPE agent for monitoring:

- hosts: vpnservers:masters:proxies:cdns:docker1:w1
- name: Include a play
  include: nbz4live.nagios-nrpe-server.yml

#################### Ubuntu auto upgrades

- hosts: vpnservers:masters:proxies:cdns:docker1:w1
- name: Include a play
  include: apt.unattended-upgrades.yml

#################### Nginx + Letsencrypt ( Proxies )

- hosts:
    - proxies
  become: True
  gather_facts: yes
  roles:
    - xoom.nginx-le

#################### Nginx ( CDNS )

- name: Nginx CDNS
  import_playbook: __xoom.nginx-le.cdn.yml 

#################### Nginx ( Edge )

- name: Nginx Edge
  import_playbook: __xoom.nginx-le.edge.yml 

#################### Telegraf agent

- name: Install Telegraf
  import_playbook: telegraf.yml
