---


- name: reload systemctl
  command: systemctl daemon-reload
  when:   ansible_service_mgr == "systemd"

- name: restart firewall
  systemd:
    state: restarted
    daemon_reload: yes
    name: iptables


- name: rsyslog restart
  systemd:
    state: restarted
    daemon_reload: yes
    name: rsyslog


- name: restart systemd-journald
  systemd:
    state: restarted
    daemon_reload: yes
    name: systemd-journald
